name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install core module dependencies
        run: npm install
      - name: Build core module
        run: npm run build

      - name: Stage dependency for sample projects
        run: npm run prep-sample

      - name: Install JS sample dependencies
        working-directory: samples/imposter-sample-javascript
        run: npm install
      - name: Build JS sample
        working-directory: samples/imposter-sample-javascript
        run: npm run build

      - name: Install TS sample dependencies
        working-directory: samples/imposter-sample-typescript
        run: npm install
      - name: Build TS sample
        working-directory: samples/imposter-sample-typescript
        run: npm run build

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
